version: "3.8"
services:
  chatbot-api:
    build: ./service-chatbot
    ports:
      - "3001:3001"
    depends_on:
      - ollama
    volumes:
      - ./service-chatbot:/app
    environment:
      - NODE_ENV=production

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data:
